import { Person } from "./types";

export const initialData: Person[] = [
  {
    id: "1",
    name: "Priya Sharma",
    email: "priya.sharma@example.com",
    age: 28,
    role: "User",
    department: "Engineering",
    location: "Mumbai",
  },
  {
    id: "2",
    name: "Rohan Gupta",
    email: "rohan.gupta@example.com",
    age: 34,
    role: "Manager",
    department: "Marketing",
    location: "Delhi",
  },
  {
    id: "3",
    name: "Anjali Patel",
    email: "anjali.patel@example.com",
    age: 42,
    role: "Admin",
    department: "HR",
    location: "Bengaluru",
  },
  {
    id: "4",
    name: "Vikram Singh",
    email: "vikram.singh@example.com",
    age: 25,
    role: "User",
    department: "Sales",
    location: "Chennai",
  },
  {
    id: "5",
    name: "Sneha Reddy",
    email: "sneha.reddy@example.com",
    age: 31,
    role: "User",
    department: "Engineering",
    location: "Hyderabad",
  },
  {
    id: "6",
    name: "Arjun Kumar",
    email: "arjun.kumar@example.com",
    age: 29,
    role: "Guest",
    department: "Support",
    location: "Kolkata",
  },
  {
    id: "7",
    name: "Neha Desai",
    email: "neha.desai@example.com",
    age: 48,
    role: "Manager",
    department: "Finance",
    location: "Mumbai",
  },
  {
    id: "8",
    name: "Aditya Mehta",
    email: "aditya.mehta@example.com",
    age: 22,
    role: "User",
    department: "Marketing",
    location: "Pune",
  },
  {
    id: "9",
    name: "Pooja Joshi",
    email: "pooja.joshi@example.com",
    age: 35,
    role: "Admin",
    department: "IT",
    location: "Bengaluru",
  },
  {
    id: "10",
    name: "Karan Malhotra",
    email: "karan.malhotra@example.com",
    age: 40,
    role: "Manager",
    department: "Engineering",
    location: "Delhi",
  },
  {
    id: "11",
    name: "Isha Nair",
    email: "isha.nair@example.com",
    age: 27,
    role: "User",
    department: "Sales",
    location: "Ahmedabad",
  },
  {
    id: "12",
    name: "Siddharth Rao",
    email: "siddharth.rao@example.com",
    age: 33,
    role: "Guest",
    department: "Support",
    location: "Pune",
  },
  {
    id: "13",
    name: "Divya Iyer",
    email: "divya.iyer@example.com",
    age: 45,
    role: "Admin",
    department: "IT",
    location: "Mumbai",
  },
  {
    id: "14",
    name: "Raj Verma",
    email: "raj.verma@example.com",
    age: 26,
    role: "User",
    department: "HR",
    location: "Delhi",
  },
  {
    id: "15",
    name: "Meera Krishnan",
    email: "meera.krishnan@example.com",
    age: 39,
    role: "Manager",
    department: "Finance",
    location: "Chennai",
  },
];

export const defaultColumns: (keyof Person)[] = [
  "name",
  "email",
  "age",
  "role",
];
